name: selene
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.7.0

dependencies:
    animated_visibility: ^0.0.4
    appbar_animated: ^0.0.3
    archive: ^4.0.4
    auto_route: ^9.2.2
    change_case: ^2.2.0
    collection: ^1.19.1
    cupertino_icons: ^1.0.8
    dartx: ^1.2.0
    device_info_plus: ^11.3.3
    drift: ^2.26.0
    drift_flutter: ^0.2.4
    dynamic_color: ^1.7.0
    easy_localization: ^3.0.7+1
    easy_localization_loader: ^2.0.2
    expand_widget: ^3.1.1
    expandable_text: ^2.3.0
    file_picker: ^9.0.2
    flex_color_picker: ^3.7.0
    flex_color_scheme: ^8.1.1
    flex_seed_scheme: ^3.5.0
    flexible_wrap: ^1.0.5
    flutter:
        sdk: flutter
    flutter_card_swiper: ^7.0.2
    flutter_launcher_icons: ^0.14.3
    flutter_layout_grid: ^2.0.7
    flutter_native_splash: ^2.4.5
    flutter_riverpod: ^2.6.1
    flutter_slidable: ^4.0.0
    flutter_svg: ^2.0.17
    freezed_annotation: ^2.4.4
    hive_ce: ^2.10.1
    hive_ce_flutter: ^2.2.0
    isar:
        version: 3.1.8
        hosted: https://pub.isar-community.dev/
    isar_flutter_libs: # contains Isar Core
        version: 3.1.8
        hosted: https://pub.isar-community.dev/
    json_annotation: ^4.9.0
    lorem_ipsum: ^0.0.3
    material_symbols_icons: ^4.2805.1
    path: ^1.9.1
    path_provider: ^2.1.5
    permission_handler: ^11.4.0
    responsive_framework: ^1.5.1
    riverpod_annotation: ^2.6.1
    rxdart: ^0.28.0
    stream_transform: ^2.1.1
    system_theme: ^3.1.2
    xml: ^6.5.0

dependency_overrides:
    analyzer: '>=5.2.0 <7.0.0'

dev_dependencies:
    auto_route_generator: ^9.0.0
    build_runner: ^2.4.6
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    freezed: ^2.5.7
    hive_ce_generator: ^1.8.1
    isar_generator:
        version: 3.1.8
        hosted: https://pub.isar-community.dev/
    json_serializable: ^6.9.0
    package_rename: ^1.8.0
    riverpod_generator: ^2.3.3
    riverpod_lint: ^2.1.1
    drift_dev: ^2.26.0

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/fonts/
        - assets/icons/
        - assets/images/
        - assets/launcher/
        - assets/splash/

flutter_launcher_icons:
    # Android
    android: true
    image_path_android: 'assets/launcher/android/icon.png'
    min_sdk_android: 21 # android min sdk min:16, default 21
    adaptive_icon_background: 'assets/launcher/android/background.png'
    adaptive_icon_foreground: 'assets/launcher/android/foreground.png'
    adaptive_icon_foreground_inset: 0
    adaptive_icon_monochrome: 'assets/launcher/android/monochrome.png'

    # iOS
    ios: true
    image_path_ios: 'assets/launcher/ios/icon.png'
    remove_alpha_channel_ios: true

    # Windows
    windows:
        generate: true
        image_path: 'assets/launcher/windows/icon.png'

    macos:
        generate: true
        image_path: 'assets/launcher/macos/icon.png'

flutter_native_splash:
    background_image: assets/splash/background.png
    image: assets/splash/icon.png
    # Android
    android_12:
        image: assets/splash/foreground.png
        color: '#111318'

package_rename_config:
    android:
        app_name: Selene
        package_name: dev.nploetz.selene
        override_old_package: com.example.selene
        lang: kotlin
    ios:
        app_name: Selene
        bundle_name: selene
        package_name: dev.nploetz.selene
    linux:
        app_name: Selene
        package_name: dev.nploetz.selene
        exe_name: selene-linux-x64
    windows:
        app_name: Selene
        organization: nploetz
        copyright_notice: Copyright ©️ 2025 nploetz. All rights reserved.
        exe_name: selene-win32
    macos:
        app_name: Selene
        package_name: dev.nploetz.selene
        copyright_notice: Copyright ©️ 2025 nploetz. All rights reserved.
